apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devopscourse
  name: todo-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
