apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/frontend-deployment.yaml
  - manifests/frontend-service.yaml
images:
  - name: FRONTEND/IMAGE
    newName: artomulkahainen/todos-frontend
