apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopscourse
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: artomulkahainen/pingpong:19
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PW
              valueFrom:
                secretKeyRef:
                  name: postgres-pw
                  key: POSTGRES_PW
