apiVersion: v1
kind: Service
metadata:
  namespace: devopscourse
  name: todo-backend-service
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
