apiVersion: v1
kind: Secret
metadata:
    namespace: devopscourse
    name: postgres-pw
data:
    POSTGRES_PW: ENC[AES256_GCM,data:NAKG53JWX6a4RQ==,iv:+Ajj1OQNmVrJ5ZObAbrSJpZOn/R2YcQYkuxQ32CSufE=,tag:Pz+99B4tZtnZlbPbLYLhvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cvemuvaaaapfkpn0734uhwdp66a9kk6t8zr6gxv74gl2ntyzrsjsxdmxky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c09hSmx2dHl0OXhZTTMz
            OGlJTE81SUNKOHZEbkpTaTJVSDlaT0ptRENBCnR0eThWVGxZZFNra2F0aXZtbDRr
            RkRLYTNXOU95ZDRQL2w2OFk1UVFLWk0KLS0tIHRJdlBlYkZnM3dycHdxc0xoeWFt
            c3JsWkpiYkpCSXpCbkVad2VtUjhBeTQKw1ifCaoN5U/9swM+Gh6LfxHRuydqnshR
            Czx/YMpo28dtxghPiUZHy/zc9PXefaH2lvtLicaGY9CgMLS6C1Vt4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T10:50:06Z"
    mac: ENC[AES256_GCM,data:awoC3aOyazye1Qd3nJKhTg36AYSPJqQjd9UFLx/YS+I9cFlE9/T5mWkiBZhHsexLVwT2fT3kpbXKf5Kw5gLbhadamhBL3uE8c6e1NwC2sOIM3f0UXJ4cmoiZ+TA3IYBskrFWhPK5eM9J+TCkpp+NF4fLlZf5hUL5rN7zJrvFL6U=,iv:3Ac3s21pbA1OVsslUyMKbtcxJMsPf2cUPjIxvHM8C6k=,tag:LNeuk9SCZXdtjvSm2dUi1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
