apiVersion: v1
kind: Service
metadata:
  namespace: devopscourse
  name: pingpong-service
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
